language: csharp
mono: none
dotnet: 3.1.101
script:
 - dotnet restore
 - dotnet build
 - VSTEST_RUNNER_PROGRESS=0 VSTEST_RUNNER_COLOR=1 dotnet test --no-build -p:VsTestConsolePath="$TRAVIS_BUILD_DIR/console/vstest.console.dll"
 - VSTEST_RUNNER_PROGRESS=1 VSTEST_RUNNER_COLOR=0 dotnet test --no-build -p:VsTestConsolePath="$TRAVIS_BUILD_DIR/console/vstest.console.dll"
 - VSTEST_RUNNER_PROGRESS=1 VSTEST_RUNNER_COLOR=1 dotnet test --no-build -p:VsTestConsolePath="$TRAVIS_BUILD_DIR/console/vstest.console.dll"
